/**
 * Government Template Definitions
 * 
 * Official GSTN/GST Portal template formats for GSTR-1.
 */

// Govt template columns (official format)
export const GOVT_TEMPLATE_COLUMNS = {
  b2b: [
    { key: 'gstin', label: 'GSTIN', required: true },
    { key: 'invoice_number', label: 'Invoice Number', required: true },
    { key: 'invoice_date', label: 'Invoice Date', required: true },
    { key: 'invoice_value', label: 'Invoice Value', required: true },
    { key: 'place_of_supply', label: 'Place of Supply', required: false },
    { key: 'reverse_charge', label: 'Reverse Charge', required: false },
    { key: 'invoice_type', label: 'Invoice Type', required: false },
    { key: 'hsn_code', label: 'HSN Code', required: false },
    { key: 'taxable_value', label: 'Taxable Value', required: true },
    { key: 'igst_rate', label: 'IGST Rate', required: false },
    { key: 'igst_amount', label: 'IGST Amount', required: false },
    { key: 'cgst_rate', label: 'CGST Rate', required: false },
    { key: 'cgst_amount', label: 'CGST Amount', required: false },
    { key: 'sgst_rate', label: 'SGST Rate', required: false },
    { key: 'sgst_amount', label: 'SGST Amount', required: false },
    { key: 'cess_rate', label: 'Cess Rate', required: false },
    { key: 'cess_amount', label: 'Cess Amount', required: false },
  ],
  b2cl: [
    { key: 'invoice_number', label: 'Invoice Number', required: true },
    { key: 'invoice_date', label: 'Invoice Date', required: true },
    { key: 'invoice_value', label: 'Invoice Value', required: true },
    { key: 'place_of_supply', label: 'Place of Supply', required: true },
    { key: 'hsn_code', label: 'HSN Code', required: false },
    { key: 'taxable_value', label: 'Taxable Value', required: true },
    { key: 'igst_rate', label: 'IGST Rate', required: false },
    { key: 'igst_amount', label: 'IGST Amount', required: false },
    { key: 'cess_rate', label: 'Cess Rate', required: false },
    { key: 'cess_amount', label: 'Cess Amount', required: false },
  ],
  b2cs: [
    { key: 'place_of_supply', label: 'Place of Supply', required: true },
    { key: 'supply_type', label: 'Supply Type', required: false },
    { key: 'rate', label: 'Rate', required: true },
    { key: 'taxable_value', label: 'Taxable Value', required: true },
    { key: 'igst_amount', label: 'IGST Amount', required: false },
    { key: 'cgst_amount', label: 'CGST Amount', required: false },
    { key: 'sgst_amount', label: 'SGST Amount', required: false },
    { key: 'cess_amount', label: 'Cess Amount', required: false },
  ],
  cdnr: [
    { key: 'gstin', label: 'GSTIN', required: true },
    { key: 'note_type', label: 'Note Type (C/D)', required: true },
    { key: 'note_number', label: 'Note Number', required: true },
    { key: 'note_date', label: 'Note Date', required: true },
    { key: 'invoice_number', label: 'Invoice Number', required: true },
    { key: 'invoice_date', label: 'Invoice Date', required: false },
    { key: 'note_value', label: 'Note Value', required: true },
    { key: 'place_of_supply', label: 'Place of Supply', required: false },
    { key: 'hsn_code', label: 'HSN Code', required: false },
    { key: 'taxable_value', label: 'Taxable Value', required: true },
    { key: 'igst_rate', label: 'IGST Rate', required: false },
    { key: 'igst_amount', label: 'IGST Amount', required: false },
    { key: 'cgst_rate', label: 'CGST Rate', required: false },
    { key: 'cgst_amount', label: 'CGST Amount', required: false },
    { key: 'sgst_rate', label: 'SGST Rate', required: false },
    { key: 'sgst_amount', label: 'SGST Amount', required: false },
  ],
  exports: [
    { key: 'invoice_number', label: 'Invoice Number', required: true },
    { key: 'invoice_date', label: 'Invoice Date', required: true },
    { key: 'invoice_value', label: 'Invoice Value', required: true },
    { key: 'place_of_supply', label: 'Place of Supply', required: true },
    { key: 'shipping_bill_number', label: 'Shipping Bill Number', required: false },
    { key: 'shipping_bill_date', label: 'Shipping Bill Date', required: false },
    { key: 'port_code', label: 'Port Code', required: false },
    { key: 'hsn_code', label: 'HSN Code', required: false },
    { key: 'taxable_value', label: 'Taxable Value', required: true },
    { key: 'igst_rate', label: 'IGST Rate', required: false },
    { key: 'igst_amount', label: 'IGST Amount', required: false },
  ],
  hsn: [
    { key: 'hsn_code', label: 'HSN Code', required: true },
    { key: 'description', label: 'Description', required: false },
    { key: 'uqc', label: 'UQC', required: false },
    { key: 'quantity', label: 'Quantity', required: false },
    { key: 'total_value', label: 'Total Value', required: false },
    { key: 'taxable_value', label: 'Taxable Value', required: true },
    { key: 'igst_amount', label: 'IGST Amount', required: false },
    { key: 'cgst_amount', label: 'CGST Amount', required: false },
    { key: 'sgst_amount', label: 'SGST Amount', required: false },
    { key: 'cess_amount', label: 'Cess Amount', required: false },
  ],
};

// Column header mappings for Govt template
export const GOVT_HEADER_MAPPINGS: Record<string, string[]> = {
  invoice_number: ['Invoice No', 'Invoice Number', 'Inv No', 'inv_no', 'inum', 'Bill No', 'Invoice'],
  invoice_date: ['Invoice Date', 'Inv Date', 'inv_date', 'idt', 'Date', 'Bill Date'],
  customer_name: ['Customer Name', 'Buyer Name', 'Party Name', 'Name', 'buyer_name'],
  customer_gstin: ['GSTIN', 'GSTIN/UIN', 'Customer GSTIN', 'Buyer GSTIN', 'gstin', 'ctin'],
  place_of_supply: ['Place of Supply', 'POS', 'State', 'Ship To State', 'pos'],
  invoice_value: ['Invoice Value', 'Total Amount', 'Invoice Value', 'Total', 'val', 'Grand Total'],
  taxable_value: ['Taxable Value', 'Taxable Amount', 'Base Amount', 'txval', 'Net Amount'],
  hsn_code: ['HSN Code', 'HSN', 'SAC Code', 'HSN/SAC', 'hsn', 'hsn_sc'],
  igst_rate: ['IGST Rate', 'IGST %', 'igst_rate', 'IR'],
  igst_amount: ['IGST Amount', 'IGST', 'iamt', 'IGST Tax'],
  cgst_rate: ['CGST Rate', 'CGST %', 'cgst_rate', 'CR'],
  cgst_amount: ['CGST Amount', 'CGST', 'camt', 'CGST Tax'],
  sgst_rate: ['SGST Rate', 'SGST %', 'sgst_rate', 'SR'],
  sgst_amount: ['SGST Amount', 'SGST', 'samt', 'SGST Tax'],
  cess_rate: ['Cess Rate', 'Cess %', 'csrt'],
  cess_amount: ['Cess Amount', 'Cess', 'csamt'],
  reverse_charge: ['Reverse Charge', 'RCM', 'rchrg'],
  note_type: ['Note Type', 'Type', 'CN Type', 'ntty'],
  note_number: ['Note Number', 'Credit/Debit Note No', 'nt_num'],
  note_date: ['Note Date', 'Credit/Debit Note Date', 'nt_dt'],
  note_value: ['Note Value', 'Note Amount', 'val'],
};

// Tax rates commonly used in India
export const STANDARD_TAX_RATES = [
  { rate: 0, label: '0%' },
  { rate: 0.1, label: '0.1%' },
  { rate: 0.25, label: '0.25%' },
  { rate: 1, label: '1%' },
  { rate: 1.5, label: '1.5%' },
  { rate: 3, label: '3%' },
  { rate: 5, label: '5%' },
  { rate: 7, label: '7%' },
  { rate: 12, label: '12%' },
  { rate: 18, label: '18%' },
  { rate: 28, label: '28%' },
];

// State codes
export const STATE_CODES: Record<string, string> = {
  '01': 'Jammu and Kashmir',
  '02': 'Himachal Pradesh',
  '03': 'Punjab',
  '04': 'Chandigarh',
  '05': 'Uttarakhand',
  '06': 'Haryana',
  '07': 'Delhi',
  '08': 'Rajasthan',
  '09': 'Uttar Pradesh',
  '10': 'Bihar',
  '11': 'Sikkim',
  '12': 'Arunachal Pradesh',
  '13': 'Nagaland',
  '14': 'Manipur',
  '15': 'Mizoram',
  '16': 'Tripura',
  '17': 'Meghalaya',
  '18': 'Assam',
  '19': 'West Bengal',
  '20': 'Jharkhand',
  '21': 'Odisha',
  '22': 'Chhattisgarh',
  '23': 'Madhya Pradesh',
  '24': 'Gujarat',
  '25': 'Daman and Diu',
  '26': 'Dadra and Nagar Haveli',
  '27': 'Maharashtra',
  '28': 'Andhra Pradesh (Old)',
  '29': 'Karnataka',
  '30': 'Goa',
  '31': 'Lakshadweep',
  '32': 'Kerala',
  '33': 'Tamil Nadu',
  '34': 'Puducherry',
  '35': 'Andaman and Nicobar Islands',
  '36': 'Telangana',
  '37': 'Ladakh',
  '38': 'Other Territory',
  '97': 'Other Territory',
};

// Template configuration
export const GOVT_TEMPLATE_CONFIG = {
  name: 'Government Template (GSTN)',
  description: 'Official GSTN format for GSTR-1 filing',
  version: '3.1',
  supported_sections: ['b2b', 'b2cl', 'b2cs', 'cdnr', 'cnds', 'exports', 'hsn', 'docs'],
  max_file_size: 10 * 1024 * 1024, // 10MB
  allowed_extensions: ['.xlsx', '.xls'],
};
